# cDNA_FASTQ_DIR: 
#         "data/cDNA-fastq/"

# global
OUTDIR:
  "SuRE-pipelineOutput"
ADPT_SEQ: 
  "CCTAGCTAACTATAACGGTCCTAAGGTAGCGAA"

cDNA:
  FASTQ_DIR:
    "/home/NFS/users/l.pagie/projects/LP140430_SureSeq_JvArensbergen/analyses/LP161128_Sure_pipeline_snakemake/data/cDNA-fastq"
  OUTDIR:
    "cDNA-counts"
  FASTQ_FILES:
    - test.1000.0001.fastq
    - test.1000.0002.fastq
    - test.1000.0003.fastq
    - test.1000.0004.fastq
  SAMPLES:
    K562_B1_T1: 
      - test.1000.0001.fastq
    K562_B1_T2: 
      - test.1000.0002.fastq
    K562_B2_T1: 
      - test.1000.0003.fastq
    K562_B2_T2: 
      - test.1000.0004.fastq
    MCF7_B1_T1: 
      - test.1000.0005.fastq
    MCF7_B1_T2: 
      - test.1000.0006.fastq
    MCF7_B2_T1: 
      - test.1000.0007.fastq
    MCF7_B2_T2: 
      - test.1000.0008.fastq

iPCR:
  FASTQ_DIR:
    "/home/NFS/users/l.pagie/projects/LP140430_SureSeq_JvArensbergen/analyses/LP161128_Sure_pipeline_snakemake/data/iPCR-fastq"
  OUTDIR:
    "iPCR-map"
  SAMPLES:
    iPCR1: 
      - test-R1-00.fq
      - test-R2-00.fq
    iPCR2: 
      - test-R1-00.fq.gz
      - test-R2-00.fq.gz
